name: not-rocket-science

on:
  push:
    branches: [ "test/**", "test-**" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run every day at 12:39 UTC (mid morning on the US East Coast).
    # Daily runs are done for two reasons:
    # 1. To ensure that GitHub Actions has a fresh cache to use.
    #    See https://docs.github.com/en/actions/reference/dependency-caching-reference#restrictions-for-accessing-a-cache
    # 2. To catch any issues arising from external changes.
    - cron:  '39 12 * * *'
  workflow_dispatch:
    # No particular downsides to enabling manual workflow runs, afaik?

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings -Aclippy::uninlined_format_args"
  XJ_SHOW_CMDS: "1"

jobs:
  not-rocket-science-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Provision Python via uv
        run: cli/10j provision uv

      - name: Ensure no large files were accidentally added
        run: cli/10j check-repo-file-sizes

      - name: Code linting and formatting checks
        run: cli/10j check-py

  not-rocket-science-rs-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-14, macos-15]
    runs-on: ${{ matrix.runner }}
    env:
      C2RUST_TESTED_CRATES: "-p c2rust -p c2rust-transpile -p c2rust-ast-printer"
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          workspaces: c2rust
          prefix-key: release-
          key: ${{ matrix.runner }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Provision Rust
        run: cli/10j provision rust

      - name: Build c2rust tests
        run: cd c2rust && ../cli/10j cargo test --locked --release $C2RUST_TESTED_CRATES --no-run

      - name: Run c2rust unit tests
        run: cd c2rust && ../cli/10j cargo test --locked --release $C2RUST_TESTED_CRATES

      - name: Build c2rust binaries
        run: XJ_BUILD_RS_PROFILE=release cli/10j build-rs

  not-rocket-science-rs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          workspaces: c2rust
          # No need for key since we only run this on one runner.
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install tss utility for showing timestamps
        run: curl --silent --location --output tss https://github.com/kevinburke/tss/releases/download/1.3/tss-linux-amd64 && chmod +x tss

      - name: Provision Rust
        run: cli/10j provision rust | ./tss
        shell: bash  # GitHub Actions applies pipefail only for explicitly requested bash shell.
        # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

      - name: Code linting and formatting checks
        run: cli/10j check-rs |& ./tss
        shell: bash  # GitHub Actions applies pipefail only for explicitly requested bash shell.

  not-rocket-science-ocaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract OCaml Cache Key
        id: extract
        run: echo "ocaml_key=$(python3 cli/constants.py ocaml-cache-key)" >> $GITHUB_OUTPUT

      # We don't use setup-ocaml because it would compile OCaml in the runner's
      # environment, which has libraries that aren't available to the 10j toolchain.
      # Thus, when our provisioning process would try to compile dune, it would fail.
      # This action restores a previous cache, if we have one, and populates the cache
      # if the workflow succeeds.
      # XREF:ci-opam-paths
      - name: Cache OCaml
        id: cache-ocaml
        uses: actions/cache@v4
        with:
          path: |
            ~/.opam
            ~/.local/bin/opam
          key: ${{ steps.extract.outputs.ocaml_key }}
          
      - name: Provision OCaml
        run: cli/10j provision ocaml
