name: rebuild and push containers

on:
  workflow_dispatch:
  schedule:
    # Run every Saturday at 16:39 UTC (just before noon on the US East Coast).
    - cron:  '39 16 * * 6'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        image: [fedora-42]
 
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aarnotenjin
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit timestamp
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            aarnotenjin/${{ matrix.image }}
            ghcr.io/Aarno-Labs/tenjin-${{ matrix.image }}
          tags: |
            type=sha,prefix=rev-
            type=raw,latest
            type=schedule,pattern={{date 'YYYYMMDD'}}
          labels: |
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 9

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v6
        id: push
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: .github/containerfiles/${{ matrix.image }}
          context: .github/containerfiles/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/Aarno-Labs/tenjin-${{ matrix.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
